[workspace]
authors = ["kiki <charles@skeletalstudios.com>"]
channels = ["conda-forge"]
name = "animator-pro"
platforms = ["osx-64", "osx-arm64"]
version = "1.4"

[tasks]
configure = { cmd="cmake -B _build -S . -G Ninja -DCMAKE_INSTALL_PREFIX=_install -DWITH_ANI=1 -DWITH_POCO=1" }
build = { cmd="cmake --build _build --config debug --target install", depends-on=["configure"] }
test = { cmd="ctest --test-dir _build --output-on-failure", depends-on=["build"] }
ani = { cmd="./ani", cwd="_install", depends-on=["build"] }
clean = "rm -rf _*"

[dependencies]
cmake = ">=4.1.2,<5"
ninja = ">=1.13.1,<2"
git = ">=2.51.0,<3"
